src/AppBundle/Entity/Quote.php
<?php
// src/AppBundle/Entity/Quote.php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use GuzzleHttp\Client as GuzzleClient;
use AppBundle\Model\QuoteInfo;

/**
 * @ORM\Entity
 * @ORM\Table(name="app_quote")
 */
class Quote
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Symbol")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="symbol_id", referencedColumnName="id")
     * })
     */
    private $symbol;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    private $count;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="quotes")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    public function __construct()
    {
        // your own logic
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set symbol
     *
     * @param \AppBundle\Entity\Symbol $symbol
     * @return Quote
     */
    public function setSymbol(\AppBundle\Entity\Symbol $symbol = null)
    {
        $this->symbol = $symbol;

        return $this;
    }

    /**
     * Get symbol
     *
     * @return \AppBundle\Entity\Symbol 
     */
    public function getSymbol()
    {
        return $this->symbol;
    }

    /**
     * Set count
     *
     * @param integer $count
     * @return Quote
     */
    public function setCount($count)
    {
        $this->count = $count;

        return $this;
    }

    /**
     * Get count
     *
     * @return integer 
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Set user
     *
     * @param \AppBundle\Entity\User $user
     * @return Quote
     */
    public function setUser(\AppBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \AppBundle\Entity\User 
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @return \AppBundle\Model\QuoteInfo
     */
    public function getInfo()
    {
        $client = new GuzzleClient();
        $res = $client->request('GET', 'https://query.yahooapis.com/v1/public/yql', [
            'query' => [
                'q' => sprintf(
                    'select * from yahoo.finance.quotes where symbol="%s"',
                    $this->symbol->getSymbol()
                ),
                'format' => 'json',
                'env' => 'store://datatables.org/alltableswithkeys'
            ]
        ]);
        
        $result = json_decode($res->getBody());

        return new QuoteInfo(
            $result->query->results->quote->Bid,
            $result->query->results->quote->Ask
        );
    }
}

src/AppBundle/Form/QuoteType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuoteType extends AbstractType
{
    /**
     * Quote form create
     * @param  FormBuilderInterface $builder
     * @param  array                $options
     * @return void
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('symbol', null, array('label' => 'form.symbol', 'translation_domain' => 'AppBundle'))
            ->add('count', null, array('label' => 'form.count', 'translation_domain' => 'AppBundle'));
    }
    
    /**
     * Quote form set options
     * @param  OptionsResolver $resolver
     * @return viod
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Quote'
        ));
    }

    /**
     * Get prefix
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'appbundle_quote';
    }
}

src/AppBundle/Controller/QuoteController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Quote;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;use Symfony\Component\HttpFoundation\Request;

/**
 * Quote controller.
 *
 * @Route("quote")
 */
class QuoteController extends Controller
{
    /**
     * Lists all quote entities.
     *
     * @Route("/", name="quote_index")
     * @Method("GET")
     */
    public function indexAction()
    {
        $user = $this->container->get('security.context')->getToken()->getUser();
        $em = $this->getDoctrine()->getManager();

        $quotes = $em->getRepository('AppBundle:Quote')->findByUser($user->getId());

        return $this->render(
            'AppBundle:Quote:index.html.twig',
            array(
                'quotes' => $quotes,
            )
        );
    }

    /**
     * Creates a new quote entity.
     *
     * @Route("/new", name="quote_new")
     * @Method({"GET", "POST"})
     */
    public function newAction(Request $request)
    {
        $quote = new Quote();
        $form = $this->createForm('AppBundle\Form\QuoteType', $quote);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $user = $this->container->get('security.context')->getToken()->getUser();
            $quote->setUser($user);
        }
        
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($quote);
            $em->flush($quote);

            return $this->redirectToRoute('quote_show', array('id' => $quote->getId()));
        }

        return $this->render(
            'AppBundle:Quote:new.html.twig',
            array(
                'quote' => $quote,
                'form' => $form->createView(),
            )
        );
    }

    /**
     * Finds and displays a quote entity.
     *
     * @Route("/{id}", name="quote_show")
     * @Method("GET")
     */
    public function showAction(Quote $quote)
    {
        $user = $this->container->get('security.context')->getToken()->getUser();
        
        if ($quote->getUser()->getID() != $user->getId())
            throw $this->createNotFoundException('Not find');

        $deleteForm = $this->createDeleteForm($quote);

        return $this->render(
            'AppBundle:Quote:show.html.twig',
            array(
                'quote' => $quote,
                'delete_form' => $deleteForm->createView(),
            )
        );
    }

    /**
     * Displays a form to edit an existing quote entity.
     *
     * @Route("/{id}/edit", name="quote_edit")
     * @Method({"GET", "POST"})
     */
    public function editAction(Request $request, Quote $quote)
    {
        $user = $this->container->get('security.context')->getToken()->getUser();
        
        if ($quote->getUser()->getID() != $user->getId())
            throw $this->createNotFoundException('Not find');

        $deleteForm = $this->createDeleteForm($quote);
        $editForm = $this->createForm('AppBundle\Form\QuoteType', $quote);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted()) {
            $quote->setUser($user);
        }

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('quote_edit', array('id' => $quote->getId()));
        }

        return $this->render(
            'AppBundle:Quote:edit.html.twig',
            array(
                'quote' => $quote,
                'edit_form' => $editForm->createView(),
                'delete_form' => $deleteForm->createView(),
            )
        );
    }

    /**
     * Deletes a quote entity.
     *
     * @Route("/{id}", name="quote_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, Quote $quote)
    {
        $user = $this->container->get('security.context')->getToken()->getUser();
        
        if ($quote->getUser()->getID() != $user->getId())
            throw $this->createNotFoundException('Not find');
    
        $form = $this->createDeleteForm($quote);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($quote);
            $em->flush($quote);
        }

        return $this->redirectToRoute('quote_index');
    }

    /**
     * Creates a form to delete a quote entity.
     *
     * @param Quote $quote The quote entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Quote $quote)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('quote_delete', array('id' => $quote->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}

src/AppBundle/Resources/views/Quote/edit.html.twig
{% extends "AppBundle::layout.html.twig" %}

{% block content %}
    <h1>Quote edit</h1>

    {{ form_start(edit_form) }}
        {{ form_widget(edit_form) }}
        {# <input type="submit" value="Edit" /> #}
        <button type="submit" class="btn btn-default">Edit</button>
    {{ form_end(edit_form) }}

    <ul>
        <li>
            <a href="{{ path('quote_index') }}">Back to the list</a>
        </li>
        <li>
            {{ form_start(delete_form) }}
                {# <input type="submit" value="Delete"> #}
                <button type="submit" class="btn btn-default">Delete</button>
            {{ form_end(delete_form) }}
        </li>
    </ul>
{% endblock content %}

src/AppBundle/Resources/views/Quote/index.html.twig
{% extends "AppBundle::layout.html.twig" %}

{% block content %}
    <h1>Quotes list</h1>

    <table class="table table-condensed table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Symbol</th>
                <th>Count</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for quote in quotes %}
            <tr>
                <td><a href="{{ path('quote_show', { 'id': quote.id }) }}">{{ quote.id }}</a></td>
                <td>{{ quote.symbol }}</td>
                <td>{{ quote.count }}</td>
                <td>
                    <ul>
                        <li>
                            <a href="{{ path('quote_show', { 'id': quote.id }) }}">show</a>
                        </li>
                        <li>
                            <a href="{{ path('quote_edit', { 'id': quote.id }) }}">edit</a>
                        </li>
                    </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('quote_new') }}" class="btn btn-default">Create a new quote</a>
{% endblock content %}

src/AppBundle/Resources/views/Quote/new.html.twig
{% extends "AppBundle::layout.html.twig" %}

{% block content %}
    <h1>Quote creation</h1>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        {# <input type="submit" value="Create" /> #}
        <button type="submit" class="btn btn-default">Create</button>
    {{ form_end(form) }}

    <ul>
        <li>
            <a href="{{ path('quote_index') }}">Back to the list</a>
        </li>
    </ul>
{% endblock content %}

src/AppBundle/Resources/views/Quote/show.html.twig
{% extends "AppBundle::layout.html.twig" %}

{% block content %}
    <h1>Quote</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ quote.id }}</td>
            </tr>
            <tr>
                <th>Symbol</th>
                <td>{{ quote.symbol }}</td>
            </tr>
            <tr>
                <th>Count</th>
                <td>{{ quote.count }}</td>
            </tr>
            <tr>
                <th>Bid</th>
                <td>{{ quote.info.bid }}</td>
            </tr>
            <tr>
                <th>Ask</th>
                <td>{{ quote.info.ask }}</td>
            </tr>
        </tbody>
    </table>

    <ul>
        <li>
            <a href="{{ path('quote_index') }}">Back to the list</a>
        </li>
        <li>
            <a href="{{ path('quote_edit', { 'id': quote.id }) }}">Edit</a>
        </li>
        <li>
            {{ form_start(delete_form) }}
                {# <input type="submit" value="Delete"> #}
                <button type="submit" class="btn btn-default">Delete</button>
            {{ form_end(delete_form) }}
        </li>
    </ul>
{% endblock content %}